-- ============================================
-- AI Data Engineering Monitor — Database Schema
-- ============================================
-- Run this against your Supabase / PostgreSQL database.
-- Usage: psql $DATABASE_URL -f sql/schema.sql

-- 1. Customers table — stores cleaned Telco churn data
CREATE TABLE IF NOT EXISTS customers (
    customer_id         VARCHAR(20) PRIMARY KEY,
    gender              VARCHAR(10),
    senior_citizen      SMALLINT,
    partner             VARCHAR(5),
    dependents          VARCHAR(5),
    tenure              INTEGER,
    phone_service       VARCHAR(5),
    multiple_lines      VARCHAR(20),
    internet_service    VARCHAR(20),
    online_security     VARCHAR(20),
    online_backup       VARCHAR(20),
    device_protection   VARCHAR(20),
    tech_support        VARCHAR(20),
    streaming_tv        VARCHAR(20),
    streaming_movies    VARCHAR(20),
    contract            VARCHAR(20),
    paperless_billing   VARCHAR(5),
    payment_method      VARCHAR(30),
    monthly_charges     NUMERIC(10, 2),
    total_charges       NUMERIC(10, 2),
    churn               VARCHAR(5),
    ingested_at         TIMESTAMP DEFAULT NOW()
);

-- 2. Pipeline runs — one row per pipeline execution
CREATE TABLE IF NOT EXISTS pipeline_runs (
    run_id              VARCHAR(36) PRIMARY KEY,
    pipeline_name       VARCHAR(100) NOT NULL,
    start_time          TIMESTAMP NOT NULL,
    end_time            TIMESTAMP,
    status              VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    rows_received       INTEGER DEFAULT 0,
    rows_processed      INTEGER DEFAULT 0,
    rows_rejected       INTEGER DEFAULT 0,
    error_message       TEXT,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_pipeline_runs_status ON pipeline_runs(status);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_name   ON pipeline_runs(pipeline_name);
CREATE INDEX IF NOT EXISTS idx_pipeline_runs_time   ON pipeline_runs(start_time DESC);

-- 3. Data quality results — one row per quality check
CREATE TABLE IF NOT EXISTS data_quality_results (
    id                  SERIAL PRIMARY KEY,
    run_id              VARCHAR(36) NOT NULL REFERENCES pipeline_runs(run_id),
    check_name          VARCHAR(100) NOT NULL,
    status              VARCHAR(10) NOT NULL,       -- PASS / FAIL / WARN
    severity            VARCHAR(10) NOT NULL,       -- LOW / MEDIUM / HIGH / CRITICAL
    actual_value        TEXT,
    expected_value      TEXT,
    message             TEXT,
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dqr_run_id ON data_quality_results(run_id);
CREATE INDEX IF NOT EXISTS idx_dqr_status ON data_quality_results(status);

-- 4. Anomaly events — flagged anomalies
CREATE TABLE IF NOT EXISTS anomaly_events (
    id                  SERIAL PRIMARY KEY,
    run_id              VARCHAR(36) NOT NULL REFERENCES pipeline_runs(run_id),
    anomaly_type        VARCHAR(100) NOT NULL,
    severity            VARCHAR(10) NOT NULL,
    description         TEXT,
    detected_at         TIMESTAMP DEFAULT NOW(),
    resolved            BOOLEAN DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_anomaly_run_id ON anomaly_events(run_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_type   ON anomaly_events(anomaly_type);

-- 5. AI incident reports — generated by the OpenAI agent
CREATE TABLE IF NOT EXISTS incident_reports (
    id                  SERIAL PRIMARY KEY,
    run_id              VARCHAR(36) NOT NULL REFERENCES pipeline_runs(run_id),
    incident_title      VARCHAR(255),
    severity            VARCHAR(10),
    summary             TEXT,
    confirmed_facts     TEXT,           -- JSON array stored as text
    possible_root_causes TEXT,          -- JSON array stored as text
    business_impact     TEXT,
    recommended_actions TEXT,           -- JSON array stored as text
    confidence          NUMERIC(4, 2),
    created_at          TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_incident_run_id ON incident_reports(run_id);
